version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - 3010:3000
    volumes:
      - ./backend/src:/usr/src/app
  frontend:
    build: ./frontend
    ports:
      - 3020:3000
    volumes:
      - ./frontend/src:/usr/src/app
