version: "3.9"
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/src/.env
    ports:
      - 3010:3000
    volumes:
      - ./backend/src:/usr/src/app
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/src/.env
    environment:
      - WDS_SOCKET_PORT=3020
    ports:
      - 3020:3000
    volumes:
      - ./frontend/src:/usr/src/app
